version: 2    
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
    groups:
      artifacts:
        patterns:
          - actions/upload-artifact
          - actions/download-artifact
